$pdf_mode = 1;
$interaction = 'nonstopmode';
$synctex = 1;
$out_dir = 'build';
$aux_dir = 'build';

$ENV{'TEXINPUTS'} = './access//:' . ($ENV{'TEXINPUTS'} || '');
$ENV{'BIBINPUTS'} = '../../:' . ($ENV{'BIBINPUTS'} || '');

@default_files = ('main.tex');
